blueprint:
  product name: online book
  description: This is an online book
  user groups: 
    - site admin:
        description: Super user of the site. Can access all features
    - author
    - anonymous reader
    - registered user
  key features: 
    - read a book online
    - leave comments for any page
  user interfaces:
    - browser:
        scope: MVP
    - mobile app:
        scope: future
  

